spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test
    username: test
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

      